### PR TITLE
Fix mypy and pylint warnings

### PR DESCRIPTION
**Pull request by ameer424**

### CODE REVIEW

**Comment by ameer424** [comment]
Now both pylint and mypy warnings has been fixed.

**Comment by anttipham** [comment]
I think `# pylint: disable=consider-using-with` and `# pylint: disable=wildcard-import,unused-wildcard-import` shouldn't be used. You should fix those normally.

Some of the disables can be done globally in `.pylintrc`. (Done)

**Comment by ameer424** [comment]
Fixed. If there is no other comments, merge it.

**Review by anttipham — APPROVED** [review]
Some code initializes empty lists without specifying the type and you've just disabled the warning on that. But the QA is over, so we will just ignore this minor warning.

**Pull request merged**
