### PR TITLE
slack implementation docs

### PR DESCRIPTION
**Pull request by dhakalsamundra**
Docs with the slack implementation info. As we can not implement it as we do not have enterprise account.

### CODE REVIEW

**Comment by ameer424** [comment]
Why slack implementation is not done in the same way as google calendar events and google groups? I mean we could have been started the implementation and do it as good as we can and then we can write a file about how to finilize.

**Comment by dhakalsamundra** [comment]
> Why slack implementation is not done in the same way as google calendar events and google groups? I mean we could have been started the implementation and do it as good as we can and then we can write a file about how to finilize.

We can not do anything as we can not test it until we have a specific role. So I added the code as docs in the file.

**Comment by ameer424** [comment]
Does customer know about this decision?

**Comment by dhakalsamundra** [comment]
> Does customer know about this decision?

They know that's why they have not given Slack some credentials as we are non employees.

**Comment by anttipham** [comment]
"We can not do anything as we can not test it until we have a specific role. So I added the code as docs in the file."
Excuses :D. Start coding or ask customer their opinion.

**Review by anttipham — CHANGES_REQUESTED** [review]
Ew PDF.
Make it into .md file (like README.md).

**Comment by dhakalsamundra** [comment]
> "We can not do anything as we can not test it until we have a specific role. So I added the code as docs in the file." Excuses :D. Start coding or ask customers their opinion.
I contact customers and they said to make full information docs is enough

**Comment by anttipham** [comment]
Ah, that's good! It's always good to check with the customer

**Comment by anttipham** [comment]
When you're done, I will merge this to master. We don't want a large PDF file hanging in our commit tree...

**Comment by anttipham** [comment]
Documentations should be in /docs folder. /src stands for source code.

**Review by anttipham — CHANGES_REQUESTED** [review]
Make slack.py into normal .py file.
- Don't put everything into triple quotes. Make it... you know... into normal code.
- Add type hints
- Make proper docstring (view, for example, any lyyti python file for more details)

**Comment by anttipham** [comment]
Also name slack.py better. For me, it seems stupid to have slack.slack module (package name "slack", module name "slack")

**Comment by dhakalsamundra** [comment]
> Make slack.py into normal .py file.
> 
> * Don't put everything into triple quotes. Make it... you know... into normal code.
> * Add type hints
> * Make proper docstring (view, for example, any lyyti python file for more details)

what do you mean by adding a type hint? Also, what do you mean by make slack.py to normal .py file ?

**Comment by anttipham** [comment]
> what do you mean by adding a type hint? Also, what do you mean by make slack.py to normal .py file ?

Type hint is type hint:
https://docs.python.org/3/library/typing.html

Normal Python file:
- Add type hints
- Make proper docstring (view, for example, any lyyti python file for more details)

**Comment by dhakalsamundra** [comment]
> > what do you mean by adding a type hint? Also, what do you mean by make slack.py to normal .py file ?
> 
> Type hint is type hint: https://docs.python.org/3/library/typing.html
> 
> Normal Python file:
> 
> * Don't put everything into triple quotes. Make it... you know... into normal code.
> * Add type hints
> * Make proper docstring (view, for example, any lyyti python file for more details)

Is my new push isn't like a normal python code still?

**Comment by anttipham** [comment]
> > > what do you mean by adding a type hint? Also, what do you mean by make slack.py to normal .py file ?
> > 
> > 
> > Type hint is type hint: https://docs.python.org/3/library/typing.html
> > Normal Python file:
> > 
> > * Don't put everything into triple quotes. Make it... you know... into normal code.
> > * Add type hints
> > * Make proper docstring (view, for example, any lyyti python file for more details)
> 
> Is my new push isn't like a normal python code still?

No, it isn't. It doesn't conform to our coding style (black + PEP8).
Add type hints
Make proper docstring (view, for example, any lyyti python file for more details)

**Review by anttipham — APPROVED** [review]
QA is over. Merging

**Pull request merged**
