### PR TITLE
Change google calendar link to google calendar id

### PR DESCRIPTION
**Pull request by ameer424**

### CODE REVIEW

**Comment by anttipham** [comment]
Would you also refactor lyyti_event.google_calendar_link to lyyti_event.google_calendar_id?

**Comment by anttipham** [comment]
Maybe removing the related tests might be good because I think that the tests can't be run without the utils function that was deleted

**Comment by ameer424** [comment]
I will refactor that. After we merge this one I will create ticket for removing related tests. I will give that to Sammundra, Hayder, Milo, or Akseli because after this and the other ask I will have enough hours.

**Comment by ameer424** [comment]
> Would you also refactor lyyti_event.google_calendar_link to lyyti_event.google_calendar_id?

This one is refactored. If there is no other issues, merge this pull request to master.

**Review by anttipham — APPROVED** [review]
As long as the code was refactored properly, this should be good

**Pull request merged**
